### ISSUE TITLE
Restarting Isolate unhandled_promise_rejection: UnhandledPromiseRejection, last request: "UDF: testing.js:stop"

### ISSUE THREAD

**Issue by MrCsabaToth** [get-convex/convex-backend#19]
I'm trying to use a precompiled ARM binary on an M3 MacBook and running AI Town. I followed the instructions, however the binary back-end displays this, while the AI Town backend tells "No default world found". Not sure how to proceed. I peeked into the SQLite3 DB locally, and it kinda seems empty even though I'm executing the script which supposed to seed / scaffold stuff.
Ref https://github.com/a16z-infra/ai-town/issues/256

**Comment by nipunn1313** [comment]
Hi - https://github.com/a16z-infra/ai-town/issues/256 seems like the right place to get help with this since it appears to be related to something about setting up ai-town.

`UnhandledPromiseRejection` happens whenever the convex backend runs javascript whose promise rejects (fails) - so it appears convex-backend is working as expected.

Hopefully you're able to get ai-town working from the instructions!

**Comment by nipunn1313** [comment]
going to close it - but feel free to reopen if there's directly an issue with convex-backend that you discover.
