### ISSUE TITLE
Use Prisma as an alternative ORM

### ISSUE THREAD

**Issue by alexwork1611** [get-convex/convex-backend#20]
From my understanding, Convex only lets you use its own ORM. Is it possible to use Prisma instead? Thanks!

**Comment by ikhare** [comment]
Hi @alexwork1611, Convex isn't a traditional database system. There is no SQL, so Prisma or existing ORMs cannot be used. The TypeScript `ctx.db` API is directly translated to calls in the database. `mutation` functions in Convex are a transaction as a whole.

Hope that helps. I also recommend reading through the first couple pages of the [Tour](https://docs.convex.dev/get-started) to clarify some of these concepts.

**Comment by nipunn1313** [comment]
We do love prisma as a concept. We want the query experience to be just as good. You can check out some of the rationale in this explanation (which does refer to prisma in fact!).
https://stack.convex.dev/convex-vs-relational-databases

Would love to hear any feedback on the query syntax for Convex.

**Comment by alexwork1611** [comment]
Thank you for the replies! All that makes sense. I think a really nice pattern would be extending existing models with custom methods. For example, one may want to query a specific table (e.g. `users`). After this retrieval, it would be great if there was an option to define a method that gets that user's posts (Laravel has this with its database ORM).

I know you can have vanilla classes that have a database model as its single constructor function parameter, but it'd be interesting if there was an opinionated pattern defined in Convex's API.

That being said, would you simply recommend devs to make vanilla classes that have this functionality?

Thank you!

**Comment by ikhare** [comment]
Yep, the general idea is that core Convex APIs only expose what the database is actually good at (we do have a few exceptions to this). Then, you build patterns on top of this in code.

One analogy is to think about normal code and in-memory data. You have a class that abstracts all access to a set of things, including multiple lists of data, and exposes only application-specific APIs. For example, an`addFriend` method might add a couple of rows and update some counts, but it is entirely hidden from the calling entity. Instead of in-memory data, you're going to be talking to persisted data.

I do hope that we can build a higher-level set of recommended patterns at some point. For now you can chat with the community about what might be the best answer for your product: https://convex.dev/community

**Comment by alexwork1611** [comment]
Sounds good. Hope you can come up with an intuitive, developer-friendly API. Thank you!
